#  To run in the foreground
#  > docker-compose up
#
#  To run in the background and tail the logs
#  > docker-compose up -d
#  > docker-compose logs -f
#
#  Subsequent builds for any changes in dockerfile.
#  > docker-compose build

version: "3.8"
services:
  backend:
    build:
      dockerfile: Dockerfile
      context: backend
    ports:
      - 4000:4000
  frontend:
    build:
      dockerfile: Dockerfile
      context: frontend
    environment:
      api: backend
    ports:
      - 5000:5000
